# Generated by Django 2.1 on 2018-08-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('iata', models.CharField(max_length=100)),
                ('icao', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('timezone', models.FloatField()),
                ('dst', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['airport_id'],
            },
        ),
    ]
